version: "3.8"

services:
  react-app:
    image: node:18
    container_name: react-vite-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
